### PR TITLE
added ec2

### PR DESCRIPTION
**Pull request by 582Bamfo**
This is to add ec2 as one of the resource we have covered

### CODE REVIEW

**Review by KoBrane — COMMENTED** [review]
This is wrong

**Comment by KoBrane** [comment]
You needed to make it caps

**Review by KoBrane — CHANGES_REQUESTED** [review]
Push back once done

**Comment by 582Bamfo** [comment]
NOTED

**Review by KoBrane — APPROVED** [review]
All good

**Comment by 582Bamfo** [comment]
thank you

**Pull request merged**
